[package]
name = "bitcoin-explorer"
version = "1.2.20"
edition = "2018"
readme = "README.md"
license-file = "LICENSE.txt"
keywords = ["blockchain", "bitcoin", "explorer", "parser", "concurrency"]
description = "High Performance Blockchain Deserializer"
homepage = "https://github.com/Congyuwang/Rusty-Bitcoin-Explorer"
repository = "https://github.com/Congyuwang/Rusty-Bitcoin-Explorer"
exclude = ["./resources"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["on-disk-utxo"]
on-disk-utxo = ["rocksdb", "tempdir"]

[dependencies]
# TODO: https://github.com/rust-bitcoin/rust-bitcoin/pull/1847
bitcoin = { git = "https://github.com/liuchengxu/rust-bitcoin", rev = "e38bc26da49fded5158b43b5f1cfa530bc47716e", features = ["serde"] }
par-iter-sync = "^0.1.11"
byteorder = "^1.4"
serde = "^1.0"
rayon = "^1.5"
log = "^0.4"
leveldb = "=0.8.6"
num_cpus = "^1.13.0"
db-key = "=0.0.5"
hash_hasher = "^2.0.3"
rocksdb = { version = "0.20.1", optional = true }
tempdir = { version = "^0.3.7", optional = true }

[lib]
name = "bitcoin_explorer"
crate-type = ["lib"]
doctest = false
