name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: nightly
            components: rustfmt

      - name: Run fmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: stable
            components: rust-src, clippy

      - name: Run clippy
        run: |
          cargo clippy --locked --all-features --all-targets --manifest-path Cargo.toml -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # with:
        # lfs: true

    - name: Build
      run: |
        cargo build --verbose --release
        cargo build --verbose --release --no-default-features

    # TODO: fix tests
    # - name: Checkout LFS objects
      # run: git lfs checkout

    # - name: Run tests default
      # run: cargo test --release --package bitcoin-explorer -- --test-threads=1 --show-output

    # - name: Run tests no-default
      # run: cargo test --release --no-default-features --package bitcoin-explorer -- --test-threads=1 --show-output
